
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module lab1_demo(

	//////////// CLOCK //////////
	input 		          		CLOCK2_50,
	input 		          		CLOCK3_50,
	input 		          		CLOCK4_50,
	input 		          		CLOCK_50,

	//////////// KEY //////////
	input 		     [3:0]		KEY,

	//////////// SW //////////
	input 		     [9:0]		SW,

	//////////// LED //////////
	output		     [9:0]		LEDR,

	//////////// Seg7 //////////
	output		     [6:0]		HEX0,
	output		     [6:0]		HEX1,
	output		     [6:0]		HEX2,
	output		     [6:0]		HEX3,
	output		     [6:0]		HEX4,
	output		     [6:0]		HEX5,

	//////////// Audio //////////
	input 		          		AUD_ADCDAT,
	inout 		          		AUD_ADCLRCK,
	inout 		          		AUD_BCLK,
	output		          		AUD_DACDAT,
	inout 		          		AUD_DACLRCK,
	output		          		AUD_XCK,

	//////////// I2C for Audio and Video-In //////////
	output		          		FPGA_I2C_SCLK,
	inout 		          		FPGA_I2C_SDAT
);



//=======================================================
//  REG/WIRE declarations
//=======================================================


wire clock_12mhz;

pll_clk pll(
		.refclk   (CLOCK2_50),   //  refclk.clk
		.rst      (SW[0]),      //   reset.reset
		.outclk_0 (clock_12mhz)	
);

i2c_av_config setting_audio_chip(
	 .clk(CLOCK2_50),
	 .reset(SW[0]),
    .i2c_sclk(FPGA_I2C_SCLK),
    .i2c_sdat(FPGA_I2C_SDAT),
    .status(LEDR[3:0])
);

wavegen_codec wave_out(
    .i_clk(clock_12mhz),
    .reset(SW[0]),
    .wave_sel(SW[9:7]),
    .noise_in(SW[4]),
	 .inc_freq(SW[5]),
	 .amp		 (SW[6]),
	 .filter	 (SW[1]),
	 .duty_cycle (SW[2]),
	 
    .AUD_ADCDAT (AUD_ADCDAT),
	 .AUD_ADCLRCK(AUD_ADCLRCK),
	 .AUD_BCLK   (AUD_BCLK),
	 .AUD_DACDAT (AUD_DACDAT),
	 .AUD_DACLRCK(AUD_DACLRCK)
);

assign AUD_XCK = clock_12mhz;
assign LEDR[9:4] = SW[9:4];

//=======================================================
//  Structural coding
//=======================================================



endmodule
