
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module audio_equalizer_24b(

	//////////// CLOCK //////////
	input 		          		CLOCK2_50,
	input 		          		CLOCK3_50,
	input 		          		CLOCK4_50,
	input 		          		CLOCK_50,

	//////////// KEY //////////
	input 		     [3:0]		KEY,

	//////////// SW //////////
	input 		     [9:0]		SW,

	//////////// LED //////////
	output		     [9:0]		LEDR,

	//////////// Seg7 //////////
	output		     [6:0]		HEX0,
	output		     [6:0]		HEX1,
	output		     [6:0]		HEX2,
	output		     [6:0]		HEX3,
	output		     [6:0]		HEX4,
	output		     [6:0]		HEX5,

	//////////// Audio //////////
	input 		          		AUD_ADCDAT,
	inout 		          		AUD_ADCLRCK,
	inout 		          		AUD_BCLK,
	output		          		AUD_DACDAT,
	inout 		          		AUD_DACLRCK,
	output		          		AUD_XCK,

	//////////// I2C for Audio and Video-In //////////
	output		          		FPGA_I2C_SCLK,
	inout 		          		FPGA_I2C_SDAT
);



//=======================================================
//  REG/WIRE declarations
//=======================================================

wire clock_12mhz;

clk_pll pll(
		.refclk   (CLOCK2_50),   //  refclk.clk
		.rst      (~KEY[0]),      //   reset.reset
		.outclk_0 (clock_12mhz)	
);

i2c_av_config setting_audio_chip(
	 .clk(CLOCK2_50),
	 .reset(~KEY[0]),
    .i2c_sclk(FPGA_I2C_SCLK),
    .i2c_sdat(FPGA_I2C_SDAT),
    .status(LEDR[3:0])
);

wavegen_codec wave_out(
    .i_clk		 (clock_12mhz),
    .reset		 (~KEY[0]),
	 .filter_equalizer (SW[0]),
	 .gain_sel_lp   (SW[3:1]),
	 .gain_sel_bp   (SW[6:4]),
	 .gain_sel_hp   (SW[9:7]),
    .AUD_ADCDAT (AUD_ADCDAT),
	 .filter_sel    (SW[2:1]),
	 .AUD_ADCLRCK(AUD_ADCLRCK),
	 .AUD_BCLK   (AUD_BCLK),
	 .AUD_DACDAT (AUD_DACDAT),
	 .AUD_DACLRCK(AUD_DACLRCK),
	 .key			(~KEY[0]),
	 .counter_o(LEDR[9:7])
);



assign AUD_XCK = clock_12mhz;



//=======================================================
//  Structural coding
//=======================================================



endmodule
